/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddButton: typeof import('./components/AddButton.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    DashBoard: typeof import('./components/DashBoard.vue')['default']
    Header: typeof import('./components/Header/Header.vue')['default']
    HeaderAppBar: typeof import('./components/Header/HeaderAppBar.vue')['default']
    HeaderDrawer: typeof import('./components/Header/HeaderDrawer.vue')['default']
    HeaderUserMenu: typeof import('./components/Header/HeaderUserMenu.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LoginForm: typeof import('./components/Login/LoginForm.vue')['default']
    PontoCard: typeof import('./components/Pontos/PontoCard.vue')['default']
    ProfileCard: typeof import('./components/Profile/ProfileCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserForm: typeof import('./components/Usuarios/UserForm.vue')['default']
    UserTable: typeof import('./components/Usuarios/UserTable.vue')['default']
  }
}
