/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/favoritos': RouteRecordInfo<'/favoritos', '/favoritos', Record<never, never>, Record<never, never>>,
    '/home': RouteRecordInfo<'/home', '/home', Record<never, never>, Record<never, never>>,
    '/Hospedagens/': RouteRecordInfo<'/Hospedagens/', '/Hospedagens', Record<never, never>, Record<never, never>>,
    '/Hospedagens/nova': RouteRecordInfo<'/Hospedagens/nova', '/Hospedagens/nova', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/MaisAcessados': RouteRecordInfo<'/MaisAcessados', '/MaisAcessados', Record<never, never>, Record<never, never>>,
    '/Pontos/[id]': RouteRecordInfo<'/Pontos/[id]', '/Pontos/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/Pontos/novo': RouteRecordInfo<'/Pontos/novo', '/Pontos/novo', Record<never, never>, Record<never, never>>,
    '/profile': RouteRecordInfo<'/profile', '/profile', Record<never, never>, Record<never, never>>,
    '/Usuarios/': RouteRecordInfo<'/Usuarios/', '/Usuarios', Record<never, never>, Record<never, never>>,
    '/Usuarios/novo': RouteRecordInfo<'/Usuarios/novo', '/Usuarios/novo', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/favoritos.vue': {
      routes: '/favoritos'
      views: never
    }
    'src/pages/home.vue': {
      routes: '/home'
      views: never
    }
    'src/pages/Hospedagens/index.vue': {
      routes: '/Hospedagens/'
      views: never
    }
    'src/pages/Hospedagens/nova.vue': {
      routes: '/Hospedagens/nova'
      views: never
    }
    'src/pages/login.vue': {
      routes: '/login'
      views: never
    }
    'src/pages/MaisAcessados.vue': {
      routes: '/MaisAcessados'
      views: never
    }
    'src/pages/Pontos/[id].vue': {
      routes: '/Pontos/[id]'
      views: never
    }
    'src/pages/Pontos/novo.vue': {
      routes: '/Pontos/novo'
      views: never
    }
    'src/pages/profile.vue': {
      routes: '/profile'
      views: never
    }
    'src/pages/Usuarios/index.vue': {
      routes: '/Usuarios/'
      views: never
    }
    'src/pages/Usuarios/novo.vue': {
      routes: '/Usuarios/novo'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
